### ISSUE TITLE
How is the pose data used in conditioning during inference?

### ISSUE THREAD

**Issue by r3sist-uniq** [commaai/commavq#20]
The pose data are given as 6 real valued numbers, per frame. How are these values used in conditioning the model? 

The talk mentions the use of `np.digitize` to tokenize the poses, which would allow for the subsequent pass through the embedding layer. But what are the bin values? 

And are the pose values prepended before the BOS token while inferencing for every frame we need to condition? Then what does this mean about the maximum context length of the model? How would we condition it again after doing it once in the starting?

**Comment by YassineYousfi** [comment]
The model shared in the repo is not conditioned on the pose data and cannot be inferenced with it. We might open source a conditional model in the future, but this repo's main goal hasn't been reached yet: improve unconditional GPTs speed and/or quality.

This is how the conditioning would work:
- np.digitize the 6 numbers to a sane number of bins (e.g. 1024)
- shift them all to non-overlapping digits which increases the vocabulary size, this is probably not necessary but safer to do
- prepend them before each frame tokens, no need to use a BOS token, since they play the role of a BOS token
- the model will predict pose tokens and frame tokens, so the model can condition itself. Or you can override its predictions to make it do something else
